[package]
name = "chronos-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chronos-rs"
path = "src/main.rs"

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"], optional = true }
reqwest = { version = "0.11", features = ["stream", "json"] }
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
safetensors = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive", "env"] }
anyhow = "1"
byteorder = "1"
indicatif = "0.17"
sha2 = "0.10"
base64 = "0.22"
tokio-util = { version = "0.7", features = ["io"] }
candle-core = { version = "0.8", features = ["accelerate"] }
candle-nn   = { version = "0.8", features = ["accelerate"] }

[profile.release]
opt-level = 3


[features]
python = ["dep:pyo3"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
